version: '3.8'

services:
  mongodb:
    image: mongo:7
    command: mongod --replSet rs0 --bind_ip_all --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-init:
    image: mongo:7
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      bash -c "
        sleep 5 &&
        mongosh --host mongodb:27017 --quiet --eval '
          try {
            var result = rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongodb:27017\"}]});
            if (result.ok === 1) {
              print(\"Replica set initialized successfully\");
            } else {
              print(\"Replica set initialization result:\", JSON.stringify(result));
            }
          } catch (e) {
            if (e.message && e.message.includes(\"already initialized\")) {
              print(\"Replica set already initialized\");
            } else {
              print(\"Error initializing replica set:\", e.message);
              throw e;
            }
          }
        ' || echo 'Replica set initialization completed'
      "
    restart: "no"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/?replicaSet=rs0&directConnection=true
      - DB_NAME=wrongo
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=password
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/", "--user=admin", "--password=password"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data: 